
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 16 20:59:52 CST 2016
//----------------------------------------------------

package BackEnd.Analizadores.XML;

/** CUP generated class containing symbol constants. */
public class Simbolo2 {
  /* terminals */
  public static final int Archsi = 8;
  public static final int Fechaf = 7;
  public static final int Archsf = 9;
  public static final int Cadena = 15;
  public static final int Nombrei = 4;
  public static final int Ruta = 16;
  public static final int rutai = 12;
  public static final int EOF = 0;
  public static final int Nombref = 5;
  public static final int rutaf = 13;
  public static final int Archivoi = 10;
  public static final int Fecha = 14;
  public static final int error = 1;
  public static final int Archivof = 11;
  public static final int Proyectoi = 2;
  public static final int Fechai = 6;
  public static final int Proyectof = 3;
}

